Fair/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace Fair.Models
{
    public class Document
    {
        public int Id { get; set; }

        public int SearchId { get; set; }
        public Search Search { get; set; }

        [Required]
        [MaxLength(255)]
        public string Name { get; set; }

        public int? LatestRevisionId { get; set; }
        [ForeignKey("LatestRevisionId")]
        public Revision LatestRevision { get; set; }

        [InverseProperty("Document")]
        public List<Revision> Revisions { get; set; } = new List<Revision>();
    }

    [Table("Revisions")]
    public class Revision
    {
        public int Id { get; set; }

        public int DocumentId { get; set; }
        public Document Document { get; set; }

        public int Number { get; set; }

        public int AuthorId { get; set; }
        public User Author { get; set; }

        public int FileId { get; set; }
        public File File { get; set; }

        public string Notes { get; set; }

        public DateTime Timestamp { get; set; } = DateTime.Now;
    }

    public class File
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(255)]
        public string Name { get; set; }

        [MaxLength(255)]
        public string ContentType { get; set; }

        public DateTime Timestamp { get; set; } = DateTime.Now;

        public int OwnerId { get; set; }
        public User Owner { get; set; }

        public byte[] Content { get; set; }

        [NotMapped]
        public int Length => Content.Length;

        public System.IO.Stream OpenReadStream()
        {
            return new System.IO.MemoryStream(Content, false);
        }

        public static File FromUploadedFile(IFormFile uploadedFile, int ownerId)
        {
            var file = new Models.File
            {
                Name = System.IO.Path.GetFileName(uploadedFile.FileName),
                ContentType = uploadedFile.ContentType,
                OwnerId = ownerId
            };

            using (var memoryStream = new System.IO.MemoryStream())
            {
                uploadedFile.CopyTo(memoryStream);
                file.Content = memoryStream.ToArray();
            }

            return file;
        }
    }
}

Fair/Controllers/DocumentsController.cs
using System.Linq;
using Fair.Models;
using Fair.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Fair.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly SearchService searchService;
        private readonly DocumentService documentService;
        private readonly ILogger<DocumentsController> logger;

        public DocumentsController(SearchService searchService, DocumentService documentService, ILogger<DocumentsController> logger)
        {
            this.searchService = searchService;
            this.documentService = documentService;
            this.logger = logger;
        }

        public IActionResult List(int searchId)
        {
            var search = searchService.GetSearch(searchId);
            ViewBag.Search = search;
            ViewBag.PhoneInterviews = search.Applications.Where(a => a.IsAdvancedToPhoneInterview == true).ToList();
            ViewBag.CampusInterviews = search.Applications.Where(a => a.IsAdvancedToCampusInterview == true).ToList();
            return View(documentService.GetDocuments(searchId));
        }

        public IActionResult View(int searchId, int documentId)
        {
            ViewBag.Search = searchService.GetSearch(searchId);
            return View(documentService.GetDocument(documentId));
        }

        [HttpGet]
        public IActionResult Add(int searchId)
        {
            ViewBag.Search = searchService.GetSearch(searchId);
            return View();
        }

        [HttpPost]
        public IActionResult Add(int searchId, string name, string notes, IFormFile uploadedFile)
        {
            var document = new Document
            {
                SearchId = searchId,
                Name = name
            };
            documentService.AddDocument(document);
            documentService.SaveChanges();

            var user = Models.User.PrincipalToUser(User);
            var revision = new Revision
            {
                DocumentId = document.Id,
                Number = 1,
                AuthorId = user.Id,
                Notes = notes,
                File = Models.File.FromUploadedFile(uploadedFile, user.Id)
            };
            document.Revisions.Add(revision);
            document.LatestRevision = revision;
            documentService.SaveChanges();

            logger.LogInformation("{username} created document {documentId}", user.Username, document.Id);

            return Redirect($"View/{document.Id}");
        }

        [HttpGet("Searches/{searchId}/Documents/{documentId}/Revisions/Add")]
        public IActionResult AddRevision(int searchId, int documentId)
        {
            ViewBag.Search = searchService.GetSearch(searchId);
            ViewBag.Document = documentService.GetDocument(documentId);
            return View();
        }

        [HttpPost("Searches/{searchId}/Documents/{documentId}/Revisions/Add")]
        public IActionResult AddRevision(int searchId, int documentId, string notes, IFormFile uploadedFile)
        {
            var document = documentService.GetDocument(documentId);
            var user = Models.User.PrincipalToUser(User);
            var revision = new Revision
            {
                DocumentId = documentId,
                Number = document.LatestRevision.Number + 1,
                AuthorId = user.Id,
                Notes = notes,
                File = Models.File.FromUploadedFile(uploadedFile, user.Id)
            };
            document.Revisions.Add(revision);
            document.LatestRevision = revision;
            documentService.SaveChanges();

            logger.LogInformation("{username} added revision {revisionNumber} to document {documentId}",
                user.Username, revision.Number, documentId);

            return Redirect($"../../View/{documentId}");
        }

        [HttpGet("Searches/{searchId}/Documents/{documentId}/Revisions/{revisionNumber}/Edit")]
        public IActionResult EditRevision(int searchId, int documentId, int revisionNumber)
        {
            var document = documentService.GetDocument(documentId);
            ViewBag.Document = document;
            ViewBag.Search = searchService.GetSearch(searchId);
            return View(document.Revisions[document.Revisions.Count - revisionNumber]);
        }

        [HttpPost("Searches/{searchId}/Documents/{documentId}/Revisions/{revisionNumber}/Edit")]
        public IActionResult EditRevision(int searchId, int documentId, int revisionNumber, string notes)
        {
            var document = documentService.GetDocument(documentId);
            var revision = document.Revisions[document.Revisions.Count - revisionNumber];
            revision.Notes = notes;
            documentService.SaveChanges();

            return Redirect($"../../../View/{documentId}");
        }
    }
}

Fair/Controllers/FilesController.cs
using Fair.Services;
using Microsoft.AspNetCore.Mvc;

namespace Fair.Controllers
{
    public class FilesController : Controller
    {
        private readonly FileService fileService;

        public FilesController(FileService fileService)
        {
            this.fileService = fileService;
        }

        public IActionResult View(int id)
        {
            var file = fileService.GetFile(id);
            return File(file.OpenReadStream(), file.ContentType);
        }

        public IActionResult Download(int id)
        {
            var file = fileService.GetFile(id);
            return File(file.OpenReadStream(), file.ContentType, file.Name);
        }
    }
}

Fair/Controllers/SearchesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Fair.Models;
using Fair.Security;
using Fair.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Fair.Controllers
{
    public class SearchesController : Controller
    {
        private readonly SearchService searchService;
        private readonly DepartmentService departmentService;
        private readonly ApplicationTemplateService applicationTemplateService;
        private readonly IAuthorizationService authService;
        private readonly ILogger<SearchesController> logger;

        public SearchesController(SearchService searchService, DepartmentService departmentService,
            ApplicationTemplateService applicationTemplateService, IAuthorizationService authService,
            ILogger<SearchesController> logger)
        {
            this.searchService = searchService;
            this.departmentService = departmentService;
            this.applicationTemplateService = applicationTemplateService;
            this.authService = authService;
            this.logger = logger;
        }

        public IActionResult List()
        {
            return View(searchService.GetSearches(Models.User.PrincipalToUser(User)));
        }

        public IActionResult View(int id)
        {
            var search = searchService.GetSearch(id);
            ViewBag.PhoneInterviews = search.Applications.Where(a => a.IsAdvancedToPhoneInterview == true).ToList();
            ViewBag.CampusInterviews = search.Applications.Where(a => a.IsAdvancedToCampusInterview == true).ToList();

            return View(searchService.GetSearch(id));
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var search = new Search();
            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch"); // auth resource cannot be null
            if (!authResult.Succeeded)
                return Forbid();

            if (User.HasClaim(claim => claim.Type == FairClaims.DepartmentChair.ToString()))
            {
                int departmentId = int.Parse(User.FindFirst(FairClaims.DepartmentChair.ToString()).Value);
                search.DepartmentId = departmentId;
                search.Department = departmentService.GetDepartment(departmentId);
            }

            ViewBag.ApplicationTemplates = applicationTemplateService.GetApplicationTemplates().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name
            });

            return View(search);
        }

        [HttpPost]
        public async Task<IActionResult> Add(Search search, List<int> committeeMemberIds)
        {
            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch");
            if (!authResult.Succeeded)
                return Forbid();

            searchService.AddSearch(search);
            searchService.SaveChanges();

            foreach (var committeeMemberId in committeeMemberIds)
                search.CommitteeMembers.Add(new CommitteeMember(search.Id, committeeMemberId));
            searchService.SaveChanges();

            logger.LogInformation("{username} created search {searchId}", User.FindFirst(ClaimTypes.Name).Value, search.Id);

            return RedirectToAction(nameof(View), new { id = search.Id });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.ApplicationTemplates = applicationTemplateService.GetApplicationTemplates().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name
            });
            return View(searchService.GetSearch(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Search update, List<int> committeeMemberIds)
        {
            var search = searchService.GetSearch(id);
            search.Position = update.Position;
            search.ApplicationTemplateId = update.ApplicationTemplateId;

            search.SearchStartDate = update.SearchStartDate;
            search.ReviewStartDate = update.ReviewStartDate;
            search.PhoneInterviewStartDate = update.PhoneInterviewStartDate;
            search.CampusInterviewStartDate = update.CampusInterviewStartDate;
            search.SearchCloseDate = update.SearchCloseDate;

            search.DepartmentId = update.DepartmentId;
            search.DepartmentChairId = update.DepartmentChairId;
            search.CommitteeChairId = update.CommitteeChairId;
            search.CommitteeMembers.RemoveAll(m => !committeeMemberIds.Contains(m.UserId));
            committeeMemberIds.RemoveAll(memberId => search.CommitteeMembers.Select(m => m.UserId).Contains(memberId));
            search.CommitteeMembers.AddRange(committeeMemberIds.Select(memberId => new CommitteeMember(search.Id, memberId)));

            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch");
            if (!authResult.Succeeded)
                return Forbid();

            searchService.SaveChanges();

            logger.LogInformation("{username} updated search {searchId}", User.FindFirst(ClaimTypes.Name).Value, search.Id);

            return RedirectToAction(nameof(View), new { id });
        }
    }
}

Fair/Views/Documents/Add.cshtml
@{
  ViewData["Title"] = "New Document";
  var search = ViewBag.Search;
}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="List">Searches</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">@search.Name</a></li>
    <li class="breadcrumb-item"><a href="List">Documents</a></li>
    <li class="breadcrumb-item active">New Document</li>
  </ol>
</nav>

<form method="post" enctype="multipart/form-data">
  <div class="form-group">
    <label for="name">Name</label>
    <input id="name" name="name" class="form-control" required>
  </div>
  <div class="form-group">
    <label for="summernote">Notes</label>
    <textarea id="summernote" name="notes" class="form-control"></textarea>
  </div>
  <div class="form-group">
    <label for="file">File</label>
    <input id="file" type="file" name="uploadedFile" class="form-control-file" required>
  </div>
  <div class="form-row mt-2">
    <a href="List" class="btn btn-secondary">Cancel</a>
    <button class="btn btn-primary ml-2">Save</button>
  </div>
</form>

@section StyleSheets{
  <link href="~/lib/summernote/summernote-bs4.css" rel="stylesheet">
}

@section Scripts{
  <script src="~/lib/summernote/summernote-bs4.min.js"></script>
  <script>
    $(function () {
      $("#summernote").summernote({
        height: 200
      });
    });
  </script>
}

Fair/Views/Documents/AddRevision.cshtml
@{
    ViewData["Title"] = "New Revision";
    var search = ViewBag.Search;
    var document = ViewBag.Document;
}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="List">Searches</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">@search.Name</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a href="../../../Documents/List">Documents</a></li>
    <li class="breadcrumb-item"><a href="../../View/@document.Id">@document.Name</a></li>
    <li class="breadcrumb-item active">New Revision</li>
  </ol>
</nav>

<form method="post" enctype="multipart/form-data">
  <div class="form-group">
    <label for="summernote">Notes</label>
    <textarea id="summernote" name="notes" class="form-control"></textarea>
  </div>
  <div class="form-group">
    <label for="file">File</label>
    <input id="file" type="file" name="uploadedFile" class="form-control-file" required>
  </div>
  <div class="form-row mt-2">
    <a href="../../View/@document.Id" class="btn btn-secondary">Cancel</a>
    <button class="btn btn-primary ml-2">Save</button>
  </div>
</form>

@section StyleSheets{
  <link href="~/lib/summernote/summernote-bs4.css" rel="stylesheet">
}

@section Scripts{
  <script src="~/lib/summernote/summernote-bs4.min.js"></script>
  <script>
    $(function () {
      $("#summernote").summernote({
        height: 200
      });
    });
  </script>
}

Fair/Views/Documents/EditRevision.cshtml
@model Revision

@{
    ViewData["Title"] = "Edit Revision";
    var search = ViewBag.Search;
    var document = ViewBag.Document;
}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="List">Searches</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">@search.Name</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a href="../../../../Documents/List">Documents</a></li>
    <li class="breadcrumb-item"><a href="../../../View/@document.Id">@document.Name</a></li>
    <li class="breadcrumb-item active">Edit Revision @Model.Number</li>
  </ol>
</nav>

<form method="post">
  <div class="form-group">
    <label for="summernote">Notes</label>
    <textarea id="summernote" name="notes" class="form-control">@Html.Raw(Model.Notes)</textarea>
  </div>
  <div class="form-row mt-2">
    <a href="../../../View/@document.Id" class="btn btn-secondary">Cancel</a>
    <button class="btn btn-primary ml-2">Save</button>
  </div>
</form>

@section StyleSheets{
  <link href="~/lib/summernote/summernote-bs4.css" rel="stylesheet">
}

@section Scripts{
  <script src="~/lib/summernote/summernote-bs4.min.js"></script>
  <script>
    $(function () {
      $("#summernote").summernote({
        height: 200
      });
    });
  </script>
}

Fair/Views/Documents/List.cshtml
@model List<Document>

@{
  ViewData["Title"] = "Documents";
  var search = ViewBag.Search;
}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="List">Searches</a></li>
    <li class="breadcrumb-item"><a asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">@search.Name</a></li>
    <li class="breadcrumb-item active">Documents</li>
  </ol>
</nav>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">Summary</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Documents (@Model.Count)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../Applications/List">Applications (@search.Applications.Count)</a>
  </li>
  @if (search.IsReviewStarted)
  {
    <li class="nav-item">
      <a class="nav-link" href="@Context.Request.PathBase/Searches/@search.Id/Applications/List?page=PhoneInterviews">
        Online Interviews
        (@ViewBag.PhoneInterviews.Count)
      </a>
    </li>
  }
  @if (search.IsPhoneInterviewStarted)
  {
    <li class="nav-item">
      <a class="nav-link" href="@Context.Request.PathBase/Searches/@search.Id/Applications/List?page=CampusInterviews">
        Campus Interviews
        (@ViewBag.CampusInterviews.Count)
      </a>
    </li>
  }
</ul>

<p class="text-right mt-2"><a href="Add" class="btn btn-primary">New Document</a></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th class="d-none d-md-table-cell">Revisions</th>
      <th class="d-none d-md-table-cell">Updated</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var document in Model)
    {
      <tr>
        <td><a href="View/@document.Id">@document.Name</a></td>
        <td class="d-none d-md-table-cell">@document.LatestRevision.Number</td>
        <td class="d-none d-md-table-cell">@document.LatestRevision.Timestamp.ToString("d")</td>
      </tr>
    }
  </tbody>
</table>

Fair/Views/Documents/View.cshtml
@model Document
@{
  ViewData["Title"] = "View Document";
  var search = ViewBag.Search;
}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="List">Searches</a></li>
    <li class="breadcrumb-item d-none d-lg-flex"><a asp-controller="Searches" asp-action="View" asp-route-id="@search.Id">@search.Name</a></li>
    <li class="breadcrumb-item"><a href="../List">Documents</a></li>
    <li class="breadcrumb-item active">@Model.Name</li>
  </ol>
</nav>

<p class="text-right mt-2"><a href="../@Model.Id/Revisions/Add" class="btn btn-primary">New Revision</a></p>

@foreach (var revision in Model.Revisions)
{
  <div class="card">
    <div class="card-header">
      Revision @revision.Number
      <small class="text-muted float-right">@revision.Author.Name on @revision.Timestamp.ToString("d")</small>
    </div>
    <div class="card-body">
      @Html.Raw(@revision.Notes)
      <a asp-controller="Files" asp-action="Download" asp-route-id="@revision.FileId" class="card-link">Download</a>
      @if (int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value) == revision.AuthorId)
      {
        <a href="../../Documents/@Model.Id/Revisions/@revision.Number/Edit" class="card-link">Edit</a>
      }
    </div>
  </div>
}