Fair/Controllers/DepartmentsController.cs
using System.Collections.Generic;
using System.Security.Claims;
using Fair.Models;
using Fair.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Fair.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly DepartmentService departmentService;
        private readonly ILogger<DepartmentsController> logger;

        public DepartmentsController(DepartmentService departmentService, ILogger<DepartmentsController> logger)
        {
            this.departmentService = departmentService;
            this.logger = logger;
        }

        public IActionResult List()
        {
            return View(departmentService.GetDepartments());
        }

        [HttpGet]
        [Authorize("IsSysAdmin")]
        public IActionResult Add()
        {
            return View(new Department());
        }

        [HttpPost]
        [Authorize("IsSysAdmin")]
        public IActionResult Add(Department department)
        {
            departmentService.AddDepartment(department);
            departmentService.SaveChanges();

            logger.LogInformation("{username} created department {departmentName}", User.FindFirst(ClaimTypes.Name).Value, department.Name);

            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        [Authorize("IsSysAdmin")]
        public IActionResult Edit(int id)
        {
            return View(departmentService.GetDepartment(id));
        }

        [HttpPost]
        [Authorize("IsSysAdmin")]
        public IActionResult Edit(int id, Department update)
        {
            var department = departmentService.GetDepartment(id);
            department.Name = update.Name;
            department.ChairId = update.ChairId;
            departmentService.SaveChanges();

            logger.LogInformation("{username} updated department {departmentId}", User.FindFirst(ClaimTypes.Name).Value, id);

            return RedirectToAction(nameof(List));
        }

        [HttpGet("/api/departments/search")]
        public List<Department> Search([FromQuery(Name = "q")]string prefix)
        {
            return departmentService.SearchByPrefix(prefix);
        }
    }
}

Fair/Controllers/SearchesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Fair.Models;
using Fair.Security;
using Fair.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Fair.Controllers
{
    public class SearchesController : Controller
    {
        private readonly SearchService searchService;
        private readonly DepartmentService departmentService;
        private readonly ApplicationTemplateService applicationTemplateService;
        private readonly IAuthorizationService authService;
        private readonly ILogger<SearchesController> logger;

        public SearchesController(SearchService searchService, DepartmentService departmentService,
            ApplicationTemplateService applicationTemplateService, IAuthorizationService authService,
            ILogger<SearchesController> logger)
        {
            this.searchService = searchService;
            this.departmentService = departmentService;
            this.applicationTemplateService = applicationTemplateService;
            this.authService = authService;
            this.logger = logger;
        }

        public IActionResult List()
        {
            return View(searchService.GetSearches(Models.User.PrincipalToUser(User)));
        }

        public IActionResult View(int id)
        {
            var search = searchService.GetSearch(id);
            ViewBag.PhoneInterviews = search.Applications.Where(a => a.IsAdvancedToPhoneInterview == true).ToList();
            ViewBag.CampusInterviews = search.Applications.Where(a => a.IsAdvancedToCampusInterview == true).ToList();

            return View(searchService.GetSearch(id));
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var search = new Search();
            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch"); // auth resource cannot be null
            if (!authResult.Succeeded)
                return Forbid();

            if (User.HasClaim(claim => claim.Type == FairClaims.DepartmentChair.ToString()))
            {
                int departmentId = int.Parse(User.FindFirst(FairClaims.DepartmentChair.ToString()).Value);
                search.DepartmentId = departmentId;
                search.Department = departmentService.GetDepartment(departmentId);
            }

            ViewBag.ApplicationTemplates = applicationTemplateService.GetApplicationTemplates().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name
            });

            return View(search);
        }

        [HttpPost]
        public async Task<IActionResult> Add(Search search, List<int> committeeMemberIds)
        {
            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch");
            if (!authResult.Succeeded)
                return Forbid();

            searchService.AddSearch(search);
            searchService.SaveChanges();

            foreach (var committeeMemberId in committeeMemberIds)
                search.CommitteeMembers.Add(new CommitteeMember(search.Id, committeeMemberId));
            searchService.SaveChanges();

            logger.LogInformation("{username} created search {searchId}", User.FindFirst(ClaimTypes.Name).Value, search.Id);

            return RedirectToAction(nameof(View), new { id = search.Id });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.ApplicationTemplates = applicationTemplateService.GetApplicationTemplates().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name
            });
            return View(searchService.GetSearch(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Search update, List<int> committeeMemberIds)
        {
            var search = searchService.GetSearch(id);
            search.Position = update.Position;
            search.ApplicationTemplateId = update.ApplicationTemplateId;

            search.SearchStartDate = update.SearchStartDate;
            search.ReviewStartDate = update.ReviewStartDate;
            search.PhoneInterviewStartDate = update.PhoneInterviewStartDate;
            search.CampusInterviewStartDate = update.CampusInterviewStartDate;
            search.SearchCloseDate = update.SearchCloseDate;

            search.DepartmentId = update.DepartmentId;
            search.DepartmentChairId = update.DepartmentChairId;
            search.CommitteeChairId = update.CommitteeChairId;
            search.CommitteeMembers.RemoveAll(m => !committeeMemberIds.Contains(m.UserId));
            committeeMemberIds.RemoveAll(memberId => search.CommitteeMembers.Select(m => m.UserId).Contains(memberId));
            search.CommitteeMembers.AddRange(committeeMemberIds.Select(memberId => new CommitteeMember(search.Id, memberId)));

            var authResult = await authService.AuthorizeAsync(User, search, "CanWriteSearch");
            if (!authResult.Succeeded)
                return Forbid();

            searchService.SaveChanges();

            logger.LogInformation("{username} updated search {searchId}", User.FindFirst(ClaimTypes.Name).Value, search.Id);

            return RedirectToAction(nameof(View), new { id });
        }
    }
}

Fair/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Security.Claims;
using Fair.Models;
using Fair.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Fair.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserService userService;
        private readonly ILogger<UsersController> logger;

        public UsersController(UserService userService, ILogger<UsersController> logger)
        {
            this.userService = userService;
            this.logger = logger;
        }

        public IActionResult List()
        {
            return View(userService.GetUsers());
        }

        [HttpGet]
        [Authorize("IsSysAdmin")]
        public IActionResult Add()
        {
            return View(new User());
        }

        [HttpPost]
        [Authorize("IsSysAdmin")]
        public IActionResult Add(User user)
        {
            userService.AddUser(user);
            userService.SaveChanges();

            logger.LogInformation("{username} added user {name}", User.FindFirst(ClaimTypes.Name).Value, user.Name);

            return RedirectToAction(nameof(List));
        }

        [HttpGet("/api/users/search")]
        public List<User> Search([FromQuery(Name = "q")]string prefix)
        {
            return userService.SearchByPrefix(prefix);
        }
    }
}

Fair/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>FAIR - @ViewData["Title"]</title>
  <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css">
  @RenderSection("StyleSheets", required: false)
</head>
<body class="container">
  <header>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      @if (User.Identity.IsAuthenticated)
      {
        <a class="navbar-brand" asp-controller="Searches" asp-action="List">
          <span class="d-none d-lg-inline">Faculty Application Information Repository</span>
          <span class="d-lg-none">FAIR</span>
        </a>
      }
      else
      {
        <span class="navbar-brand">Faculty Application Information Repository</span>
      }
      @if (User.Identity.IsAuthenticated)
      {
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" asp-controller="Searches" asp-action="List">Searches</a>
            </li>
            @if (User.HasClaim("IsSysAdmin", true.ToString()))
            {
              <li class="nav-item">
                <a class="nav-link" asp-controller="Departments" asp-action="List">Departments</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Users" asp-action="List">Users</a>
              </li>
            }
            <li class="nav-item">
              <a class="nav-link" asp-controller="Profile" asp-action="Edit">@User.FindFirst(ClaimTypes.GivenName).Value's Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
            </li>
          </ul>
        </div>
      }
    </nav>
  </header>

  <main role="main" class="p-3">
    @RenderBody()
  </main>
  <partial name="_CookieConsentPartial" />

  <footer>
    <div class="container text-center">
      <div>&copy; Copyright 2019 by Chengyu Sun.</div>
    </div>
  </footer>

  <script src="~/lib/jquery/jquery.min.js"></script>
  <script src="~/lib/popper.js/umd/popper.min.js"></script>
  <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
  @RenderSection("Scripts", required: false)
</body>
</html>